/**
 * Curated mappings from provider-qualified offering IDs to OpenRouter's
 * creator/model slug namespace. Entries are added only when both catalogs
 * identify the same underlying model.
 */
export const CANONICAL_ALIASES: Record<string, string> = {
  "gemini:gemini-2.5-flash": "google/gemini-2.5-flash",
  "gemini:gemini-2.5-flash-image": "google/gemini-2.5-flash-image",
  "gemini:gemini-2.5-flash-lite": "google/gemini-2.5-flash-lite",
  "gemini:gemini-2.5-pro": "google/gemini-2.5-pro",
  "gemini:gemini-3-flash-preview": "google/gemini-3-flash-preview",
  "gemini:gemini-3-pro-image": "google/gemini-3-pro-image",
  "gemini:gemini-3-pro-image-preview": "google/gemini-3-pro-image-preview",
  "gemini:gemini-3.1-flash-image": "google/gemini-3.1-flash-image",
  "gemini:gemini-3.1-flash-image-preview": "google/gemini-3.1-flash-image-preview",
  "gemini:gemini-3.1-flash-lite": "google/gemini-3.1-flash-lite",
  "gemini:gemini-3.1-flash-lite-image": "google/gemini-3.1-flash-lite-image",
  "gemini:gemini-3.1-flash-lite-preview": "google/gemini-3.1-flash-lite-preview",
  "gemini:gemini-3.1-pro-preview": "google/gemini-3.1-pro-preview",
  "gemini:gemini-3.1-pro-preview-customtools": "google/gemini-3.1-pro-preview-customtools",
  "gemini:gemini-3.5-flash": "google/gemini-3.5-flash",
  "gemini:gemma-4-26b-a4b-it": "google/gemma-4-26b-a4b-it",
  "gemini:gemma-4-31b-it": "google/gemma-4-31b-it",
  "gemini:lyria-3-clip-preview": "google/lyria-3-clip-preview",
  "gemini:lyria-3-pro-preview": "google/lyria-3-pro-preview",
  "github-models:cohere/cohere-command-a": "cohere/command-a",
  "github-models:deepseek/deepseek-r1": "deepseek/deepseek-r1",
  "github-models:deepseek/deepseek-r1-0528": "deepseek/deepseek-r1-0528",
  "github-models:deepseek/deepseek-v3-0324": "deepseek/deepseek-chat-v3-0324",
  "github-models:meta/llama-3.2-11b-vision-instruct": "meta-llama/llama-3.2-11b-vision-instruct",
  "github-models:meta/llama-3.3-70b-instruct": "meta-llama/llama-3.3-70b-instruct",
  "github-models:meta/llama-4-scout-17b-16e-instruct": "meta-llama/llama-4-scout",
  "github-models:meta/meta-llama-3.1-8b-instruct": "meta-llama/llama-3.1-8b-instruct",
  "github-models:microsoft/phi-4": "microsoft/phi-4",
  "github-models:openai/gpt-4.1": "openai/gpt-4.1",
  "github-models:openai/gpt-4.1-mini": "openai/gpt-4.1-mini",
  "github-models:openai/gpt-4.1-nano": "openai/gpt-4.1-nano",
  "github-models:openai/gpt-4o": "openai/gpt-4o",
  "github-models:openai/gpt-4o-mini": "openai/gpt-4o-mini",
  "github-models:openai/gpt-5": "openai/gpt-5",
  "github-models:openai/gpt-5-chat": "openai/gpt-5-chat",
  "github-models:openai/gpt-5-mini": "openai/gpt-5-mini",
  "github-models:openai/gpt-5-nano": "openai/gpt-5-nano",
  "github-models:openai/o1": "openai/o1",
  "github-models:openai/o3": "openai/o3",
  "github-models:openai/o3-mini": "openai/o3-mini",
  "github-models:openai/o4-mini": "openai/o4-mini",
  "groq:llama-3.1-8b-instant": "meta-llama/llama-3.1-8b-instruct",
  "groq:llama-3.3-70b-versatile": "meta-llama/llama-3.3-70b-instruct",
  "groq:meta-llama/llama-4-maverick-17b-128e-instruct": "meta-llama/llama-4-maverick",
  "groq:meta-llama/llama-4-scout-17b-16e-instruct": "meta-llama/llama-4-scout",
  "groq:openai/gpt-oss-20b": "openai/gpt-oss-20b",
  "groq:openai/gpt-oss-120b": "openai/gpt-oss-120b",
  "groq:openai/gpt-oss-safeguard-20b": "openai/gpt-oss-safeguard-20b",
  "groq:qwen/qwen3-32b": "qwen/qwen3-32b",
  "groq:qwen/qwen3.6-27b": "qwen/qwen3.6-27b"
};
